package com.s4bps.creditapplication.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Integer age;
	private java.lang.Boolean approved;
	private java.lang.Double money;
	private java.lang.String name;

	private java.lang.String comment;

	private java.lang.String ruleName;

	private java.lang.Integer testResult;

	public Applicant() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Boolean getApproved() {
		return this.approved;
	}

	public void setApproved(java.lang.Boolean approved) {
		this.approved = approved;
	}

	public java.lang.Double getMoney() {
		return this.money;
	}

	public void setMoney(java.lang.Double money) {
		this.money = money;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getComment() {
		return this.comment;
	}

	public void setComment(java.lang.String comment) {
		this.comment = comment;
	}

	public java.lang.String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(java.lang.String ruleName) {
		this.ruleName = ruleName;
	}

	public java.lang.Integer getTestResult() {
		return this.testResult;
	}

	public void setTestResult(java.lang.Integer testResult) {
		this.testResult = testResult;
	}

	public Applicant(java.lang.Integer age, java.lang.Boolean approved,
			java.lang.Double money, java.lang.String name,
			java.lang.String comment, java.lang.String ruleName,
			java.lang.Integer testResult) {
		this.age = age;
		this.approved = approved;
		this.money = money;
		this.name = name;
		this.comment = comment;
		this.ruleName = ruleName;
		this.testResult = testResult;
	}

}